name: Build and Deploy ASP.NET Core Static Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build ./CAPEL/CAPEL.csproj --configuration Release --no-restore

      - name: Render Razor views as static HTML
        run: |
          cd CAPEL
          dotnet restore
          dotnet run
          cp -r output/* ../public/

      - name: Create public directory if missing
        run: mkdir -p public

      - name: Create 404.html if it doesn't exist
        run: |
          if [ ! -f public/404.html ]; then
            echo '<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><title>404 - Página no encontrada</title></head><body><h1>Error 404</h1><p>La página que buscas no existe.</p></body></html>' > public/404.html
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          force_orphan: true
