name: Build and Deploy ASP.NET Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # o tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'  # Usa la versión necesaria para tu proyecto

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o release

    - name: Copy wwwroot to publish directory (for Blazor WASM or static content)
      run: |
        mkdir public
        cp -r release/wwwroot/* public/
 
